### ISSUE TITLE
Browser Open Event 

### ISSUE THREAD

**Issue by basitcubix** [immutable/unity-immutable-sdk#104]
Hey is there a event for browser open or browser closed. I want to identify if the user has closed the browser without authenticating can you please help me with that

**Comment by nattb8** [comment]
@basitcubix
If you're using the [PKCE flow for Android, iOS and macOS](https://docs.immutable.com/docs/x/sdks/unity/#android-ios-and-macos-pkce-login), you can check if the user has closed the embedded browser before authenticating by catching the exception thrown. Calling `ConnectPKCE()` will throw an `OperationCanceledException` if the user manually closes the embedded browser. See the sample app code [here](https://github.com/immutable/unity-immutable-sdk/blob/f7c56f3f66ab927d713f94c047b994fe0289f545/sample/Assets/Scripts/UnauthenticatedScript.cs#L106).

Unfortunately, there's no way to detect if the user has closed the external browser during the [Device Code Auth flow](https://docs.immutable.com/docs/x/sdks/unity/#connect-to-passport).
