### ISSUE TITLE
Eth trafser Error 

### ISSUE THREAD

**Issue by basitcubix** [immutable/unity-immutable-sdk#107]
i am getting this error on transferring eth "error quantizing transfer amount (2792006) with quantum 100000000 -> amount not multiple of token quantum, amount:" i have convert to "Gwei" and "wei" is there anything i am doing wrong?

**Comment by nattb8** [comment]
Could you please provide the logs?

**Comment by basitcubix** [comment]
2023/10/30 13:08:31.793 9926 10005 Info Unity [Browser Communications Manager] Call imxTransfer (request ID: 10f81a21-47b4-47aa-81be-662f31e1f258)
2023/10/30 13:08:32.908 9926 10005 Info Unity [Browser Communications Manager] InvokeOnPostMessageError id: CallOnHttpError message: 400
2023/10/30 13:08:32.908 9926 10005 Error Unity [Passport Implementation] id: CallOnHttpError err: 400
2023/10/30 13:08:32.909 9926 10005 Info Unity [Browser Communications Manager] InvokeOnUnityPostMessage: {"responseFor":"imxTransfer","requestId":"10f81a21-47b4-47aa-81be-662f31e1f258","success":false,"error":"error quantizing transfer amount (2795790458096641) with quantum 100000000 -> amount not multiple of token quantum, amount: {neg:false abs:[2795790458096641]} (uint64: 2795790458096641), quantum: 100000000","errorType":"TRANSFER_ERROR"}
2023/10/30 13:08:32.909 9926 10005 Info Unity [Browser Communications Manager] HandleResponse message: {"responseFor":"imxTransfer","requestId":"10f81a21-47b4-47aa-81be-662f31e1f258","success":false,"error":"error quantizing transfer amount (2795790458096641) with quantum 100000000 -> amount not multiple of token quantum, amount: {neg:false abs:[2795790458096641]} (uint64: 2795790458096641), quantum: 100000000","errorType":"TRANSFER_ERROR"}
2023/10/30 13:08:32.918 9926 10005 Error Unity error quantizing transfer amount (2795790458096641) with quantum 100000000 -> amount not multiple of token quantum, amount: {neg:false abs:[2795790458096641]} (uint64: 2795790458096641), quantum: 100000000

**Comment by basitcubix** [comment]
```c#

        private UnsignedTransferRequest(
            string type,
            long amount,
            string receiver,
            string? tokenId = null,
            string? tokenAddress = null
            )
        {
            this.Type = type;
            this.Amount = $"{amount}";
            this.TokenId = tokenId;
            this.TokenAddress = tokenAddress;
            this.Receiver = receiver;
        }

        public static UnsignedTransferRequest ETH(string receiver, long amount)
        {
            return new UnsignedTransferRequest("ETH", amount, receiver);
        }
```

**Comment by CassiusPacheco** [comment]
Hello @basitcubix, thanks for reporting this. We've identified the problem and fixed it as a new release on v0.3.1. 

Note, however, that [transfers in Unity require a pre-approval from our team](https://docs.immutable.com/docs/x/sdks/unity#immutable-x-transfer). Please reach out to us on the contact form in our docs.

Thanks

**Comment by basitcubix** [comment]
hey i am still getting the same error after getting the latest pull from your repo can you please help me

**Comment by basitcubix** [comment]
2023/10/31 17:51:27.015 10162 10210 Error Unity error quantizing transfer amount (549164697122611) with quantum 100000000 -> amount not multiple of token quantum, amount: {neg:false abs:[549164697122611]} (uint64: 549164697122611), quantum: 100000000

**Comment by CassiusPacheco** [comment]
@basitcubix do you mind sharing the code youre using to call it and the amount youre trying to transfer please?

**Comment by basitcubix** [comment]
`    public async Task<string> CreateTransferEth(string receiver, string amount)
    {
        print("Magic Wallet Manager amount: " + amount);
        try
        {
            UnsignedTransferRequest request = UnsignedTransferRequest.ETH(
                     receiver,
                     amount
                 );
            CreateTransferResponseV1 response = await passport.ImxTransfer(request);

            return "Success "+response.TransferId.ToString();
        }
        catch (Exception ex)
        {

            Debug.LogError(ex.Message);
            return ex.Message;
        }
    }`

**Comment by basitcubix** [comment]
```c#
    public async Task<string> CreateTransferEth(string receiver, string amount)
    {
        print("Magic Wallet Manager amount: " + amount);
        try
        {
            UnsignedTransferRequest request = UnsignedTransferRequest.ETH(
                     receiver,
                     amount
                 );
            CreateTransferResponseV1 response = await passport.ImxTransfer(request);

            return "Success "+response.TransferId.ToString();
        }
        catch (Exception ex)
        {

            Debug.LogError(ex.Message);
            return ex.Message;
        }
    }
```

**Comment by CassiusPacheco** [comment]
hey @basitcubix, we're looking into it

**Comment by CassiusPacheco** [comment]
@basitcubix our system limits the decimal numbers to 10 digits for ETH. That means, for your example, you’d have to use `0.0000540858` ETH which converts to `54085800000000` wei. We’ve taken on the feedback that the API error is not clear for that and we’ll update it sometime in the future.

**Comment by basitcubix** [comment]
hey thankyou so much for the help i have fixed it closing this thread now
