### ISSUE TITLE
Passport Connect Error

### ISSUE THREAD

**Issue by jromandeveloper** [immutable/unity-immutable-sdk#111]
Hello, I am trying to implement the SDK login, but I get this error `Could not signal service com.apple.WebKit.WebContent: 113: Could not find specified service`

Do you know if I am missing something? I am using XCode 15 with minimun iOS version 13.0.

**Comment by CassiusPacheco** [comment]
hello @jromandeveloper, I have not been able to replicate your issue on my side. Would you be able to send us a sample project that shows that issue so we can better debug it?

Thanks

**Comment by jromandeveloper** [comment]
Hey @CassiusPacheco thanks for answering, I tried creating a new empty project and I was able to pass this error but now I am getting an exception only in iOS, I will create a new ticket with the info.
