### ISSUE TITLE
iOS il2cppexceptionwrapper exception when connecting

### ISSUE THREAD

**Issue by jromandeveloper** [immutable/unity-immutable-sdk#112]
Hello, so I am using the SDK as stated in the [getting started docs](https://docs.immutable.com/docs/x/sdks/unity/) and it is working but only in the editor, tried testing it using Xcode 15 and I am getting this exception` libc++abi terminating with uncaught exception of type il2cppexceptionwrapper.
`
[Here](https://drive.google.com/file/d/1K-3NKBgIlAPgRtaIQWGbsGXHHJ9-Y1gm/view?usp=drive_link) you can download the project I am using to replicate the exception but it is just an empty project using Unity 2022.3.10f1 with one script to connect to IMX.

**Comment by CassiusPacheco** [comment]
Hi @jromandeveloper, thanks for raising this issue. There's a configuration required for the iOS build that minimises the stripping code level for iOS. The stripping is getting rid of the automatically generated constructors for the models.

I'll update the docs on the website to clarify that.

To unblock you, here's what you need to do to get this working:

In `Player Settings`, under the `iOS` tab, all the way to the bottom in the `Optimization` section, change the `Managed Stripping Level` to `Minimal`.

**Comment by jromandeveloper** [comment]
Thanks @CassiusPacheco it works, also there is a different problem in Android when using PKCE login that also requires to set the  Managed Stripping Level to Minimal.
