### ISSUE TITLE
iOS PKCE login stops the game

### ISSUE THREAD

**Issue by jromandeveloper** [immutable/unity-immutable-sdk#116]
Hey, I am trying to implement the PKCE login on iOS, so far it is working just fine on Android, but when trying to do the same on iOS the game just stops when trying to initialize passport and it never goes past that point and it doesn't produce any error it just totally stops, and I have been trying to fix it by moving every single setting I can think of in Unity and Xcode but not luck so far.

The normal login is working fine, but when I follow the steps to do a KPC login it just stops working, I am using Unity 2022.3.10f1 and Xcode 15, and I can replicate the error using this small test project I made by deleting every single file from my project and just leave the script and scene to log into passport.

[Test Project](https://drive.google.com/file/d/1ZJ4AVUGAmbB3fA2BdKutJDnx1kEGn-sV/view?usp=drive_link)

**Comment by nattb8** [comment]
@jromandeveloper Please try the latest code on the `main` branch.

Once again, the [fix](https://github.com/immutable/unity-immutable-sdk/pull/123) is not in the latest version [0.4.1](https://github.com/immutable/unity-immutable-sdk/releases/tag/v0.4.1). We'll be cutting another release later this week.
