### ISSUE TITLE
Android crash when login with a new account

### ISSUE THREAD

**Issue by jromandeveloper** [immutable/unity-immutable-sdk#117]
When I try to log in on Android using a new account after a few seconds the game just crashes, if it is not the first time using this account the game works as expected, I was able to reproduce it in a [new empty project](https://drive.google.com/file/d/1EhCkZMPlh8RwO-GVU5vjN5g0-47l1sp2/view?usp=sharing) , any idea why it happens?

**Comment by nattb8** [comment]
@jromandeveloper Please try the latest code on the `main` branch.

This [fix](https://github.com/immutable/unity-immutable-sdk/pull/122) is not in the newest version, [0.4.1](https://github.com/immutable/unity-immutable-sdk/releases/tag/v0.4.1). We'll be cutting another release later this week.
