### ISSUE TITLE
After Updating to 0.6.0 can't longer log in using iOS

### ISSUE THREAD

**Issue by jromandeveloper** [immutable/unity-immutable-sdk#134]
so yes, after updating to 0.6.0 can't longer log in using iOS, I had to update due to another error, I got the "looks like something went wrong screen" and the tracking id 1b1e0516ab5f535d99bb, looks like it is only working for me on mac/windows.

**Comment by nattb8** [comment]
Can you please provide a test project again? Are you still using Unity 2022.3.10f1 and Xcode 15 and running on iOS 17.1.2?

**Comment by nattb8** [comment]
> I can log in but our backend tries to validate the id token generated but it just keeps saying it is an invalid token

The ID token should be valid, especially if you use the updated logout function in v0.6.0 and log back in again. Were you trying the Sandbox or Production environment?

> I tried using the access token and the id token, also if the user was already authenticated the tokens are always just empty strings.

This should not be the case. If it is, we need to fix it. Do you get empty access and ID token strings when you use our [sample app](https://github.com/immutable/unity-immutable-sdk/tree/main/sample), too?

**Comment by jromandeveloper** [comment]
Thanks, it was my bad looks like now I need to pass the logout URL, doing it fixes my problem
