### ISSUE TITLE
Web view issue on multiple Device resolution

### ISSUE THREAD

**Issue by basitcubix** [immutable/unity-immutable-sdk#137]
I am using Google Pixel 3 my device resolution is 1080px × 2160 my web view buttons are cutting off as you can see in the picture it's working fine on the Portrait but having problems with Landscape.
![Screenshot_20231211-154821](https://github.com/immutable/unity-immutable-sdk/assets/132077089/7c724ed7-da1d-4329-9d47-c9f4cda16946)

**Comment by nattb8** [comment]
@basitcubix Can you please check if it's resolved?
