### ISSUE TITLE
Registered Off Chain Issue on Sandbox Env (access denied, use v2 api)

### ISSUE THREAD

**Issue by basitcubix** [immutable/unity-immutable-sdk#156]
I am getting this error `access denied, use v2 api` on `RegisterOffchain` on sanbox environment it was working fine last week and somehow it is stopped. FYI every thing is working fine on Production Environment.

**Comment by nattb8** [comment]
Hi @basitcubix, could you please try [v1.0.0](https://github.com/immutable/unity-immutable-sdk/releases/tag/v1.0.0) of the SDK?
