### ISSUE TITLE
Get PKCE Auth URL error: java.lang.ClassNotFoundException: com.immutable.unity.ImmutableActivity$Callback

### ISSUE THREAD

**Issue by basitcubix** [immutable/unity-immutable-sdk#172]
Using 2021.3.33 on Player Settings => Minifi => use R8 and Release if i check these two i am getting this error on ConnectImxPKCE or LoginPKCE on Android device unchecking these two and every thing works fine. This only happens after i update to latest repo.

`2024/02/23 20:50:20.737 10685 10731 Info Unity [Browser Communications Manager] Call track (request ID: df3edb4a-6895-456d-8d7b-f320a166b55b, js: callFunction("{\"fxName\":\"track\",\"requestId\":\"df3edb4a-6895-456d-8d7b-f320a166b55b\",\"data\":\"{\\\"moduleName\\\":\\\"unitySdk\\\",\\\"eventName\\\":\\\"startedConnectImxPkce\\\",\\\"properties\\\":\\\"{}\\\"}\"}"))
2024/02/23 20:50:20.738 10685 10731 Info Unity [Passport Implementation] Send auth event: ConnectingImxPKCE
2024/02/23 20:50:20.738 10685 10731 Info Unity [Browser Communications Manager] Call getPKCEAuthUrl (request ID: a1da0ef9-ee93-4f6f-96d4-47d9324ae100, js: callFunction("{\"fxName\":\"getPKCEAuthUrl\",\"requestId\":\"a1da0ef9-ee93-4f6f-96d4-47d9324ae100\",\"data\":\"\"}"))
2024/02/23 20:50:20.769 10685 10731 Info Unity [Browser Communications Manager] InvokeOnUnityPostMessage: {"responseFor":"track","requestId":"df3edb4a-6895-456d-8d7b-f320a166b55b","success":true}
2024/02/23 20:50:20.769 10685 10731 Info Unity [Browser Communications Manager] HandleResponse message: {"responseFor":"track","requestId":"df3edb4a-6895-456d-8d7b-f320a166b55b","success":true}
2024/02/23 20:50:20.770 10685 10731 Info Unity [Browser Communications Manager] InvokeOnUnityPostMessage: {"responseFor":"getPKCEAuthUrl","requestId":"a1da0ef9-ee93-4f6f-96d4-47d9324ae100","success":true,"result":"https://auth.immutable.com/authorize?response_type=code&code_challenge=9YmkMugXy8c2wDQuizYfGrhe_rOA0cXszoE1pWViD1U&code_challenge_method=S256&client_id=fcndR2fDJkVlVUFGW97A1jWLdolXmgvX&redirect_uri=wagmigame://callback&scope=openid offline_access profile email transact&state=TDj9QWL5fGY7bwZi3Fs_Xm18UINFytIWWIBQaFDwbOs&audience=platform_api"}
2024/02/23 20:50:20.770 10685 10731 Info Unity [Browser Communications Manager] HandleResponse message: {"responseFor":"getPKCEAuthUrl","requestId":"a1da0ef9-ee93-4f6f-96d4-47d9324ae100","success":true,"result":"https://auth.immutable.com/authorize?response_type=code&code_challenge=9YmkMugXy8c2wDQuizYfGrhe_rOA0cXszoE1pWViD1U&code_challenge_method=S256&client_id=fcndR2fDJkVlVUFGW97A1jWLdolXmgvX&redirect_uri=wagmigame://callback&scope=openid offline_access profile email transact&state=TDj9QWL5fGY7bwZi3Fs_Xm18UINFytIWWIBQaFDwbOs&audience=platform_api"}
2024/02/23 20:50:20.770 10685 10731 Info Unity [Passport Implementation] Send auth event: ConnectImxPKCELaunchingCustomTabs
2024/02/23 20:50:20.774 10685 10731 Info Unity [Passport Implementation] Get PKCE Auth URL error: 

> java.lang.ClassNotFoundException: com.immutable.unity.ImmutableActivity$Callback

2024/02/23 20:50:20.774 10685 10731 Info Unity [Passport Implementation] Trying to set PKCE exception...
`

**Comment by nattb8** [comment]
@basitcubix Please add a custom Proguard file to your project if Minify is enabled. Our documentation is updated with instructions [here](https://docs.immutable.com/docs/x/sdks/unity/#proguard). You can also take a look at the sample [Proguard file](https://github.com/immutable/unity-immutable-sdk/blob/main/sample/Assets/Plugins/Android/proguard-user.txt) as an example.

If everything works, please close this issue.

**Comment by basitcubix** [comment]
Hey @nattb8 thank you for the prompt response, its now working fine
