### ISSUE TITLE
Android 14 logout error 

### ISSUE THREAD

**Issue by basitcubix** [immutable/unity-immutable-sdk#177]
Using 2021.3.33 after updating my phone to android 14 Api level 33 i cant seem to login again if i logged out once and i am getting this OperationCanceledException when ever i try to logged in again.

**Comment by basitcubix** [comment]
Attaching a video for further clarification 
https://github.com/immutable/unity-immutable-sdk/assets/132077089/f80de6eb-c10c-4457-b6d6-647f2e119029

**Comment by nattb8** [comment]
@basitcubix I couldn't reproduce it. I'm also on Android 14 (Target API level 33). Please try this [PR](https://github.com/immutable/unity-immutable-sdk/pull/178) and see if the extra delay fixes your issue?

**Comment by basitcubix** [comment]
No luck still facing the issue i am using Samsung Galaxy A52 recently updated my phone everything was working fine on Android 13 though.

**Comment by basitcubix** [comment]
I have tried the said PR still no luck. I am using Samsung Galaxy A52 also tried it on Samsung s22 but not its not logging in.  Everything is working fine on android 13

**Comment by basitcubix** [comment]
I think the issue is related to Samsung phones just tried it on Google Pixel 4a(5g) and everything is working fine @nattb8 can you please verify it on Samsung Phones.

**Comment by nattb8** [comment]
@basitcubix
I tried it on a Galaxy S24 and Galaxy S24 Ultra (both on Android 14) and could not reproduce it. I also tried it on a Samsung Galaxy A52, but on Android 11, and still had no luck.

Would you be able to try increasing the delay [here](https://github.com/immutable/unity-immutable-sdk/blob/0b82c0869c798bcd866bc1210fa9629d1cac9188/Plugins/Android/ImmutableAndroid/ImmutableAndroid/src/main/java/com/immutable/unity/ImmutableActivity.java#L109) to something like 60000ms and then running the `assemble` task as described [here](https://github.com/immutable/unity-immutable-sdk/blob/0b82c0869c798bcd866bc1210fa9629d1cac9188/Plugins/Android/ImmutableAndroid/README.md)?

You can also run the `assemble` task from the terminal:

1. `cd Plugins/Android/ImmutableAndroid`
2. `./gradlew assemble`

**Comment by nattb8** [comment]
@basitcubix I've changed how we handle dismiss callback. Could you please try the updated [PR](https://github.com/immutable/unity-immutable-sdk/pull/178) again?

**Comment by basitcubix** [comment]
Hey thank you for the prompt response i have tried the latest Pr and everything is working fine again :)
