### ISSUE TITLE
Linux Server as target platform

### ISSUE THREAD

**Issue by nazarov-andrey** [immutable/unity-immutable-sdk#368]
Unity version used: 6000.0.29f1

1) Create empty project
2) Import Immutable Unity SDK and dependencies
3) Switch to Linux Server platform.

You will get following error:
**Library/PackageCache/com.immutable.passport/Runtime/ThirdParty/Gree/Assets/Plugins/WebViewObject.cs(264,20): error CS0117: 'Logger' does not contain a definition for 'Error'**

It seems to be in file **WebViewObject.cs** line 264 it should be **PassportLogger** instead of **Logger**

**Comment by nattb8** [comment]
Hi @nazarov-andrey, Linux is not supported at the moment. However, we would gladly welcome a pull request if you'd like to contribute support for it.

**Comment by nazarov-andrey** [comment]
I understand that Linux is not supported. And everything is handled properly on your side by preprocessor directives. But I have a single project for my client and backend, client uses Immutable sdk. When I am trying to compile my backend for Linux, it fails to compile. And all just by a single misprint. The line I am asking to fix is line reporting that current platform is not supported. And it's reported by not existing class **Logger** instead of proper **PassportLogger**. Request is not about supporting Linux, but about preventing breaking project compilation on platform, which do not support WebViewObject.
