### ISSUE TITLE
Unity Giving reference error on adding the package

### ISSUE THREAD

**Issue by Nishan30** [immutable/unity-immutable-sdk#96]
![image](https://github.com/immutable/unity-immutable-sdk/assets/85409544/7040c47f-a421-48a7-98da-9418e9189d83)

**Comment by nattb8** [comment]
@Nishan30 Did you install Git LFS as per the [installation pre-requisite](https://github.com/immutable/unity-immutable-sdk#installation)?

**Comment by Nishan30** [comment]
[image: image.png]
Yes. I do have git lfs. Do I need to initialize some files too?
Regards

**Comment by Nishan30** [comment]
What I am doing is creating an empty project and just adding the packages from this repo using the package manager.

**Comment by nattb8** [comment]
@Nishan30 Those errors are usually related to Git LFS. Sometimes, deleting and cloning the project is necessary if LFS was installed after cloning. The command `git lfs pull` doesn't always work.

Have you tried using the latest code on the `main` branch? It looks like you're currently using an older version (0.1.0).

Also, to confirm, your OS is Windows and is targeting a Windows platform?

**Comment by Nishan30** [comment]
No. I am actually trying to use android.

**Comment by nattb8** [comment]
I just tried loading the SDK on **Windows** and switched the **target platform to Android** (File -> Build Settings -> Select Android -> Switch Platform) and didn't see any errors. Have you switched to Android?

**Comment by Nishan30** [comment]
Yes, I did. Can you tell me the complete steps for replicating the project
on your PC? I created a new project with the 2023 version and then
added that package based on the documentation. The project is already in
Android. Also, please let me know the Unity version that you are using.

**Comment by nattb8** [comment]
I'm using 2021.3.26f1.

I opened the `sample/` project in the repository ([link](https://github.com/immutable/unity-immutable-sdk/tree/main/sample)) on Windows as it's already set up to use the SDK (See [here](https://github.com/immutable/unity-immutable-sdk/blob/main/sample/Packages/manifest.json)). See if that works for you first.

Can you also tell me what you get if you run `git lfs ls-files --all` and `git lfs env`.

**Comment by Nishan30** [comment]
Great. It worked after I made another build and directly opened the
samples. Thank you so much. I have one more question, In my game, I am
allowing the users to connect their wallet and load their NFTs that are in
their wallet. How can I implement that? Do I ask them all to create a
passport account and then do sth with that.
Regards
Nishan

**Comment by nattb8** [comment]
Yes, you have to ask them to create a Passport account first by calling `Connect()` ([link](https://github.com/immutable/unity-immutable-sdk#connect-to-passport)) or `ConnectPKCE()` (recommended for mobile - [link](https://github.com/immutable/unity-immutable-sdk#android-ios-and-macos-pkce-login)). These methods prompt users to create an account or log in to their existing one. Once the user is logged in, you can access all the [available functions](https://github.com/immutable/unity-immutable-sdk#android-ios-and-macos-pkce-login).

If you want to obtain the user's NFTs, you can use our public APIs. For example, the [list assets](https://docs.immutable.com/x/reference/#/operations/listAssets) endpoint can be used for Immutable X.

You can check out a [sample game](https://github.com/immutable/sample-passport-unity-game) that also utilises our SDK.

**Comment by Nishan2030** [comment]
Hi @nattb8. I had one question about the passport SDK. Does this SDK allow us to get the wallet address of the passport wallet in mainnet? I have a passport wallet and the wallet address that I can see in the tokentrove marketplace and the one I get in the SDK are different. What could be the reason?

**Comment by nattb8** [comment]
@Nishan2030 Yes, you should be able to get your mainnet wallet address.
When you [registered your game](https://docs.immutable.com/docs/x/sdks/unity#registering-your-game) in the [hub](https://hub.immutable.com/), did you select the Mainnet environment? 

Also, ensure when you initialise Passport to set the environment to production.

```
string environment = Immutable.Passport.Model.Environment.PRODUCTION;
Passport passport = await Passport.Init(clientId, environment, redirectUri);
```

**Comment by Nishan2030** [comment]
I fixed it. The issue was that in the hub, it was in mainnet, but the application type was website, so it was giving a different address, I changed it to mobile or desktop then it gave me the right one. Hope it might help someone later.
![image](https://github.com/immutable/unity-immutable-sdk/assets/108890002/d684e9f1-1b21-410f-853f-654f2cb0b739)
