### ISSUE TITLE
JNI: Init'd AndroidJavaObject with null ptr! on unity editor 2021.3.18

### ISSUE THREAD

**Issue by basitcubix** [immutable/unity-immutable-sdk#98]
Is there any way to test on Unity editor because I am getting this error "init'd AndroidJavaObject with null ptr", it's working fine on Android. Please share a workaround to make it work on the editor.

**Comment by dom-murray** [comment]
Hi @basitcubix you won't be able to run Android in the Unity editor as it requires Android. You will need to build to an Android device or emulator to test your scenes that integrate the SDK.
