### ISSUE TITLE
Logout issue 

### ISSUE THREAD

**Issue by basitcubix** [immutable/unity-immutable-sdk#99]
After logging in I can't seem to log out properly even after pressing logout multiple times I am using your sample app. The issue I am facing after logging out it redirects me to the connect scene after pressing the connect button browser opens for 2 seconds it logs me again with the previous account without asking which account I want to log in from. I can't seem to change the account after logging in first time.

**Comment by dom-murray** [comment]
Hi @basitcubix. Your Unity session in game is different to the Passport session in your browser. On the browser you're logging into Passport directly, which is then used to authenticate the Sample app and create a scoped session. The logout button in the sample is only ending the games session. If you would like to test with a different Passport account you can try clearing your browsers data.
